### ISSUE TITLE
usage of gmpy2 to represent bitsets

### ISSUE THREAD

**Issue by remiadon** [HMProenca/RuleList#5]
Hi, I went trough the code of this project, and found out you are using multiprecision integer to represent bitsets and compute usage for a pattern, and also compute intersection and length over those bitsets.

I am wondering what pros and cons you've found in using such data structures

Just to mention, I am the author of [scikit-mine](https://github.com/scikit-mine/scikit-mine)
and I am using roaring bitmaps to efficiently store sets of integers

**Comment by HMProenca** [comment]
Hi Remi,

Thank you for the interest. I remember thinking about that tradeoff when I
was implementing my code.

When I was considering what made more sense for my application. In general
when I built up my method I did not think I was going to scale it up for
very sparse and large datasets. If I would, that would make perfect sense
for me :). If I would apply it to n-grams, that would make a lot of sense.

I discussed this with Marvin Meeng, one of the main authors of the subgroup
discovery tool Cortana. As he points out, when you have a compressed
representation, it makes sense if most of the bitmaps are zero or above a
certain percentage. If you are storing the information for 8 instances per
int, it means that your lower bound should be at least 1/8, thus your
sparsity per item should be above 12.5%. I remember comparing the
performance or borderline cases and it did not seem of extra interest.

Given my reasoning, I always thought of adding them for people to use in
specific applications.

What was your reasoning to use it?

Cool package :)
Best,
Hugo Proenca

**Comment by HMProenca** [comment]
P.S. I mostly got inspired by the Scalable Bayesian Rule Lists paper where
they end up comparing the different implementations of bitsets (not all,
but some) and then I repeated their experiments and did some more.

[image: image.png]
from the paper

**Comment by remiadon** [comment]
@HMProenca thanks for responding.

I take good note of this comparison, I just checked at the Scalable Rule List paper, and this is quite clearly stated.

 > What was your reasoning to use it?

I currently don't have any reason to use gmpy, I was only curious. But I keep that in mind :)
