### ISSUE TITLE
Inclusion in scikit-mine ?

### ISSUE THREAD

**Issue by remiadon** [HMProenca/RuleList#6]
Hi again,

We recently shared the [project roadmap](https://github.com/scikit-mine/scikit-mine/discussions/115) from scikit-mine.
One of the algorithms we wanted to investigate is DiffNorm, but I guess the discovery part of RuleList can solve a similar task (characterize multiple transaction sets at the same time).

This would be the first use case, although RuleList offers more (predictions)

From a technical point of view, including RuleList into skmine would require a few refactors. I tried to identify a couple of them, here is the short list I came up with :
- separate classes for different tasks (one for `task=discovery` and one for `task=prediction`), or expose the discovery part via calls `discover()` like defined in skmine's API
- separate data ingestion, your current [data ingestion](https://github.com/HMProenca/RuleList/blob/6f7a144195e075d6b4fa9cc6f3370f57b1259a69/rulelist/datastructure/data.py#L20) is tied up with the model side. One could opt for a class in the `preprocessing` module, to be called before applying a RuleList Classifier. This is not very clear in my mind though...
- use roaring bitmaps, for efficiency

Mutual maintenance for RuleList would mean:
 - maintaining compatibility with the rest of the ecosystem
 - documentation

These are all suggestions, I remain open :)

**Comment by HMProenca** [comment]
Hi Rémi,

I think those are all good suggestions.
Indeed, DiffNorm and RuleList share many things, especially the encoding
and how they partition the data. Nonetheless, the way they generate
patterns, pattern vs rule, their greedy objective, and some more
miscellaneous are different.

It would be interesting to hear your suggestions in more detail to
understand clearly what you mean by such change so that I can see if they
are feasible and make a timeline for them.

Best, Hugo

**Comment by remiadon** [comment]
@HMProenca thanks for you response, I will try to be a bit more precise.

Your `RuleList` class currently wraps 2 models, defined by the `target_model` attribute, see [here](https://github.com/HMProenca/RuleList/blob/6f7a144195e075d6b4fa9cc6f3370f57b1259a69/rulelist/search/iterative_rule_search.py#L26). I think these could be separated into 2 classes, a `GaussianRuleList` class and a `CategoricalRuleList`. As this is already implemented, I evaluate this as a "minor" refactor. 

The logic behind `task=="discover"` should be exposed via a discover method if possible, so that the user just fits a model and chooses to either make predictions or get an overview on the discovered patterns, interactively. This seems a bit more tricky, and will require your input.

Concerning the `preprocessing`, for now RuleList only supports "static" a priori discretization, see [here](https://github.com/HMProenca/RuleList/blob/6f7a144195e075d6b4fa9cc6f3370f57b1259a69/rulelist/rulelist.py#L107). so it may be a good idea to explicitly call this preprocessing step from the user side, so that other methods can benefit from it.

Here is an example of the resulting syntax
```python
import pandas as pd
from skmine import GaussianRuleList  # skmine namespace ?? maybe skmine.rulelist ...
from skmine.preprocessing import StaticDicretizer # maybe already implemented in sklearn ?
from sklearn import datasets

data = datasets.load_breast_cancer()
Y = pd.Series(data.target)
X = pd.DataFrame(data.data)

model = GaussianRuleList(min_support=.2, beam_width=20)  # no `task` or `discretization` parameter
X_preproc = StaticDiscretizer().fit_transform(X)

model.fit(X_preproc, y)

model.discover()  # expose self.antecedent_description and self.consequent_description via a pandas.DataFrame for exploratory data analysis

model.predict(X[:5])  # make predictions
``` 

Last but not least, your [bitset operations](https://github.com/HMProenca/RuleList/blob/6f7a144195e075d6b4fa9cc6f3370f57b1259a69/rulelist/util/bitset_operations.py#L22) can be performed via skmine.bitmaps. I can take care of it.

Does that give you more insights ?

**Comment by HMProenca** [comment]
Hi Rémi Adon,

I agree. Some of the changes are easier than others. Some are actually very
straightforward. Would you be up to make a video call for us to discuss
some of the points in more detail?

**Comment by HMProenca** [comment]
Hi again,

I agreed with the changes we discussed and created now a new branch to start making the code compatible with scikit-mine.
